### ISSUE TITLE
some bugs or weirdness I noticed

### ISSUE THREAD

**Issue by tromp** [mozkomor/GrinGoldMiner#1]
Line 178 of kernel.cu

    if (hash.x == 0 && hash.y == 0) continue;

would cause a __syncthreads() failure if actually executed.
At odds of 1 in 2^58 that could take a while though:-)

Lines 215-291 do not account for the case where 0 < localIdx < 4.

**Comment by mozkomor** [comment]
There is no point for the continue at that point, it was just a fragment from another version. Good catch.

Excellent point on the localIdx, that must be causing the lost cycles! It should actually use similar construct as the second transfer with condition localIdx > 0.
