### ISSUE TITLE
Bad TCP packet! when using different port

### ISSUE THREAD

**Issue by garyyu** [mozkomor/GrinGoldMiner#12]
When giving a port for the server,  `Theta` command will print endless error info `Bad TCP packet! `

$ ./Theta -d 0 -a 192.168.1.107:15414

I'm using it in ubuntu.17.10-x64, not sure whether the windows version have or not same problem.

**Comment by phooton** [comment]
Works normally on windows. I tried to setup stratum node on the same port a s you. Can you post the whole output?

**Comment by phooton** [comment]
No problem, might be a good idea to improve this kind of stuff in the miner. Cheers.
