### ISSUE TITLE
Submitting invalid PoW

### ISSUE THREAD

**Issue by jaspervdm** [mozkomor/GrinGoldMiner#17]
I recently updated my node and miner to the latest commits. However the miner submits invalid PoW, it just sends a bunch of zeroes:
```
TCP OUT: {"jsonrpc":"2.0","method":"submit","id":"Stratum","params":{"height":34692,"job_id":0,"nonce":6573202393833261859,"pow":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}}
TCP IN: {"id":"Stratum","jsonrpc":"2.0","method":"submit","result":null,"error":{"code":-32502,"message":"Failed to validate solution"}}
```
This happens for every solution it submits

**Comment by phooton** [comment]
Please build both cuda and c# parts. I changed memory mapped file names to prevent multi-gpu conflicts.
