### ISSUE TITLE
trading memory for computation

### ISSUE THREAD

**Issue by tromp** [mozkomor/GrinGoldMiner#2]
Instead of storing edge endpoints in 8 bytes, what if you only store edge indices in 4 bytes,
and recompute the endpoints repeatedly when needed for sorting?

that's basically what lean miner is doing, but i never tried it in mean miner...

**Comment by mozkomor** [comment]
That could very well become the next generation of Cuckoo miners, I never considered this, I still have profile data of this new miner in my head and it it might just work when I think about it. But it could use hand optimized siphash that would use as little registers as possible. Register pressure used to my my enemy number one, it really hurts.

**Comment by mozkomor** [comment]
Confirmed speedup to 190ms with recalculating solver and other tuning. Nonce transfered to the first round and converted to 8 byte edge. Full recalculation not tested, likely little faster but also hotter.
