### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by ArchangelGr** [mozkomor/GrinGoldMiner#21]
Hello ,

i didn't manage to execute the steps on installing GoldMiner on linux. I have CUDA up but missing the process for the other step (studio, g++). Is it possible to retouch the installation guide.

Great work guys!
Thanks

**Comment by phooton** [comment]
The miner no longer works on testnet4. Use stock grin-miner in Linux. The GPU PoW for grin is being redesigned, official miner is the only one that keeps up.
