### ISSUE TITLE
CUDA launch error

### ISSUE THREAD

**Issue by LibiChai** [mozkomor/GrinGoldMiner#24]
Starting CUDA solver process on device 0
C++ trimmer not in ready state!
Console output redirection failed! Lets try to use sockets for OpenCL miner inst
ead...
CUDA launch error

**Comment by phooton** [comment]
Known bug on small fraction of machines. Can't fix without reproducing. What Windows version you have and what localization?

**Comment by lechatnieger** [comment]
Hi, same error here,
Windows 10 Pro version 1703 Build 15063.608

Localization IT

Where can i find a log, to give more detailed info?

Thank you in advance

**Comment by phooton** [comment]
There is nothing to log. I know what happens, but without being able to replicate and debug, can't fix. 

This will not happen in the final miner that will be released before mainnet. The whole miner is being rewritten.

**Comment by LibiChai** [comment]
Hi, my report :
Windows 7  sp1 build 7601
Localization zh-cn

cards:  with 6 1080ti 11 GB Ram

Nvidia Driver Version 397.64

Dotnet Core 2.2.100

Thank you in advance

**Comment by gapeman** [comment]
```
Starting CUDA solver process on device 0

TCP IN: {"id":"111","jsonrpc":"2.0","method":"login","result":"ok","error":null}


C++ trimmer not in ready state!
Console output redirection failed! Lets try to use sockets for OpenCL miner instead...
CUDA launch error
Finished in 5924ms
```

Windows 10 Enterprise
10.0.17134 N/A Build 17134
System Locale:           en-us;English (United States)
Input Locale:              en-gb;English (United Kingdom)

4x 1070, 1x 1070ti, 1x 1080ti

4GB RAM DDR 4

Nvidia Driver 417.22

DOTNET 2.2.101

**Comment by phooton** [comment]
New miner is completely removing console redirection so this problem will be irrelevant in few days.
