### ISSUE TITLE
Tried on two machines - error "System Cannot find the file specified"

### ISSUE THREAD

**Issue by oregonisaac** [mozkomor/GrinGoldMiner#25]
No other output, unable to find any error log, not sure what file it is looking for.

**Comment by oregonisaac** [comment]
Actually it turns out there was a path issue with my dot.net install.  Figured that out by trying the CLI version of the too (bat) so I could see the command attempted.  Suggest a slightly more verbose error.

**Comment by phooton** [comment]
This is only simple beta version. Final miner will be significantly easier to use and should not have dotnet core dependency.
