### ISSUE TITLE
RTX 2080 - cudaMalloc failed buffer A 4GB!

### ISSUE THREAD

**Issue by kalderonski** [mozkomor/GrinGoldMiner#26]
Hello 
When I launch the miner on windows 10 and RTX 2080, the process start but I get the following errorr an then stops
Waiting for next block, this may take a bit.
TCP IN: {"id":"Stratum","jsonrpc":"2.0","method":"job","params":{"difficulty":1,"height":4111,"job_id":0,"pre_pow":"0001000000000000100f000000005c1fea7f0208c1ae873960d0f98e0d3b837fc9a08b898d8b2f5d067f98e74b7f0cedeed42b1158649fc4638f5bc548f6296f57e09966c0968be97780b8a842957c329b2291c8e3dcf52d2558586a6eaecb416693567fe1841b2a9375ff448b7003de59752678e01774981e487a7aec9f198d5dba2acc4a50cac9b4d7f0b82768ed26721cabbe6df16becaed640c169289e7a66a15641a3b1a584aa2d192b9bdfbac99f6d86f43075896fa93cb50b85dbbb1405059e5402c5eeb1614c71c48f81d3add3520000000000002ee40000000000002770000000001cb576280000028f"}}

Starting CUDA solver process on device 0
Currently available amount of device memory: 7005339648 bytes
Total amount of device memory: 8589934592 bytes
status: out of memory
cudaMalloc failed buffer A 4GB!
CUDA terminating...
Unexpected c++ stdout data:
C++ trimmer self-terminated!
C++ trimmer not in ready state!
Unexpected data from C++ (expected #r): Currently available amount of device memory: 7005339648 bytesTotal amount of device memory: 8589934592 bytesstatus: out of memorycudaMalloc failed buffer A 4GB!CUDA terminating...#x
CUDA launch error
Finished in 5600ms

**Comment by phooton** [comment]
Is this your main OS GPU? Looks like something is eating your VRAM. Try to close any programs using GPU (chrome etc), reboot your machine and try again. You need over 7GB free to mine, you have just below the minimum. The error message is correct, you are out of memory.

**Comment by phooton** [comment]
Actually I don't think you are on latest miner version... This is how it looks on GTX 1070 8G
```
Starting CUDA solver process on device 0
Currently available amount of device memory: 7121587404 bytes
Total amount of device memory: 8589934592 bytes
Allociating buffer 1+2
Currently available amount of device memory: 39505100 bytes
CUDA device armed
```

**Comment by BravoIndia** [comment]
Hey @phooton, do you know if support for lower VRAM GPU's, such as the 1060, will be implemented in GrinGoldMiner?
Based on the optimizations outlined here: https://www.grin-forum.org/t/gpu-mean-memory-reductions/1517

**Comment by Daniel-Wang** [comment]
@phooton It looks like the crash comes from before the line `Allociating buffer 1+2 ` is printed.
https://github.com/mozkomor/GrinGoldMiner/blob/6c1c7d545495f17e5afb2f9a4b14dabff354603f/src/Cudacka/kernel.cu#L555

**Comment by phooton** [comment]
The solver needs 7079985152 bytes of memory to work and your RTX2080 only has 7005339658 free bytes and @kalderonski 2080 has only 7005339648 bytes. My GTX 1070 has 7121587404 bytes. So what on earth is happening with RTX free memory on Windows??

**Comment by sesam** [comment]
Since the numbers differ, are you using different driver versions? Maybe the driver uploads an update into the RTX memory, occupying some additional space. Either way, this Q. on varying free memory numbers is something the RTX support surely can answer :)

**Comment by phooton** [comment]
So it looks like RTX2080 and RTX2070 will require new 6GB solver on Windows 10. 

So what should work:

All GTX, RTX and AMD 8GB+ cards on Linux, Win7, Win8
All FTX and AMD 8GB+ cards on Win10

what does not likely work now

RTX 8GB cards on Win10

**Comment by kalderonski** [comment]
Yes the issue is with windows 10. i reinstalled windows 7 and with the latest build there is no issue.
Tried back with windows 10 and BETA 3 and the problem appears.
The problem is that Ryzen is not supported by windows 7, I hope you can solve it soon.

**Comment by phooton** [comment]
What is your Virtual Memory at? Is it in 30 - 50 GB range? Your last card has plenty of free memory.

**Comment by le-dawg** [comment]
I have set the "nonfunctional" ASUS units into another node that is runnign WIndows 7. WE shall see.

**Comment by phooton** [comment]
Fixed with 6GB solver.
