### ISSUE TITLE
GrinGoldMiner support for RX580 (Cuckaroo29) ?

### ISSUE THREAD

**Issue by mmelmaslouhi** [mozkomor/GrinGoldMiner#27]
First of all thanks for your contribution! 

As the title implies I was wondering if there is any update on AMD gpu's was wondering if there is already a possibility to test with a beta version or the like?

Thanks again!

**Comment by phooton** [comment]
We have new solvers and CUDA/OCL miner in dev, beta version will be out by the end of the week.
