### ISSUE TITLE
GTX 1060 6Gb

### ISSUE THREAD

**Issue by Seigneur774** [mozkomor/GrinGoldMiner#29]
HEllo, do you think a newer version of GrinGoldMiner will be released for gtx 1060 6 Gb before the mainnet lauch?

**Comment by flufy3d** [comment]
gtx 1060 6 Gb win 10 not work

**Comment by 1Romani** [comment]
GTX 1060 6 GB doesn't work on Win 10.  Please, help me to solve this problem.

**Comment by 1Romani** [comment]
@phooton please help to solve this problem.

**Comment by phooton** [comment]
Done
