### ISSUE TITLE
GTX 1080Ti - cudaMalloc failed buffer A 4GB!

### ISSUE THREAD

**Issue by qichhhhh** [mozkomor/GrinGoldMiner#32]
<img width="732" alt="_20190110185101" src="https://user-images.githubusercontent.com/24191302/50963808-b3aea680-1508-11e9-8289-3b360882700f.png">

the same as https://github.com/mozkomor/GrinGoldMiner/issues/26

OS：win 10 pro x64
GPU：GTX 1080Ti
GPU Driver version : 417.35

**Comment by phooton** [comment]
Please use latest release.
