### ISSUE TITLE
RX 480 8gb 

### ISSUE THREAD

**Issue by vadimDidenko** [mozkomor/GrinGoldMiner#36]
After start miner. 
ERROR   Listen errorThe input stream is not a valid binary format. The starting contents (in bytes) ...
and 
ERROR   Exception in # File: C:\PROJECTS\GRIN\GrinGoldMiner\src\Master\Worker.cs # Line: 215 # Membe...

**Comment by alessandroponzo** [comment]
> ERROR Exception in # File: C:\PROJECTS\GRIN\GrinGoldMiner\src\Master\Worker.cs # Line: 215 # Membe...

I got the same error Ubuntu 16.04 2xRX480

**Comment by phooton** [comment]
For some AMD cards it is needed to

`export GPU_MAX_WORKGROUP_SIZE=1024` on linux and reboot

`setx export GPU_MAX_WORKGROUP_SIZE 1024` on windows and reboot

and of course bump virtual memory at around 64GB

**Comment by vadimDidenko** [comment]
> For some AMD cards it is needed to
> 
> `export GPU_MAX_WORKGROUP_SIZE=1024` on linux and reboot
> 
> `setx export GPU_MAX_WORKGROUP_SIZE 1024` on windows and reboot
> 
> and of course bump virtual memory at around 64GB

I have the corrected variables)

**Comment by Angel996** [comment]
> For some AMD cards it is needed to
> 
> `export GPU_MAX_WORKGROUP_SIZE=1024` on linux and reboot
> 
> `setx export GPU_MAX_WORKGROUP_SIZE 1024` on windows and reboot
> 
> and of course bump virtual memory at around 64GB

On Linux it works w/o reboot, actually.
And, the miner does NOT work w/o this line.

**Comment by BehemothZ** [comment]
Hey guys, where would one put in the ssetx export GPU_MAX_WORKGROUP_SIZE 1024 on windows?
