### ISSUE TITLE
Detected 0 suitable AMD devices

### ISSUE THREAD

**Issue by zeefporto** [mozkomor/GrinGoldMiner#37]
Hi,

I got one vega 64 and tryed to mine grin,

I installed the recommended .NET Core 2.2.

i got windows 10 winver 1709 and -adrenalin-2019-edition-18.12.3-dec19 drivers .

When i start the miner i got 0 devices:

Detected 0 suitable nvidia devices
Detected 0 suitable AMD devices

What should i look ?

Thanks

**Comment by zeefporto** [comment]
worked,

but now i got:

ERROR   Exception in # File: StratumConnect.cs # Line: 146 # Member: Connect Message: Este anfitrião...
ERROR   Exception in # File: StratumConnect.cs # Line: 146 # Member: Connect Message: Uma tentativa ...

**Comment by phooton** [comment]
double check SSL setting, your stratum server addr and port

**Comment by zeefporto** [comment]
worked :)

Have to put ssl false :)

**Comment by zeefporto** [comment]
After mainlaunch can we mine to a wallet?

Regards
