### ISSUE TITLE
Only secondary hashrate on 1080ti? 

### ISSUE THREAD

**Issue by Twente-Mining** [mozkomor/GrinGoldMiner#39]
Hi i'm using the linux version of this miner, but i noticed its only giving secondary hashrate on my 11 gb 1080ti cards. Shouldn't it be able to do primary hashrate or am I wrong? 

current_primary_hashrate":0,current_secondary_hashrate":22.82

**Comment by phooton** [comment]
C31 not possible on windows

**Comment by Twente-Mining** [comment]
dude did you even READ?! 
I'm using LINUX VERSION
