### ISSUE TITLE
can we add a logging option for linux-based systems?

### ISSUE THREAD

**Issue by leifliddy** [mozkomor/GrinGoldMiner#43]
Is there a way we can enable a (normal) console logging mechanism for linux systems where the logs are sequentially written to stdout? I've created a systemd unit file and would like the output directed to a file. However, the way this miner logs to stdout is a bit odd, and it doesn't format correctly when the output is directed to a file.

**Comment by urza** [comment]
Miner already writes to log file in /logs folder, you can set the level of what gets written to this file by setting
```
<LogOptions>
    <FileMinimumLogLevel>INFO</FileMinimumLogLevel>
...
```
in your config.xml
accepted values are DEBUG, INFO, WARNING, ERROR
(DEBUG might slow down mining a little bit)

In TUI you can press L key and the console will switch to rolling mode.

**Comment by leifliddy** [comment]
Thanks! Is there a way to disable the TUI and start the service in rolling mode?

**Comment by phooton** [comment]
we are developing GrinPro.io, GGM is open source SW designed for end user
