### ISSUE TITLE
change from cuckoo29 to cuckoo31 ?

### ISSUE THREAD

**Issue by philllie** [mozkomor/GrinGoldMiner#44]
it seems, I would be way better off to mine via cuckoo31 (i am on windows) , but the miner uses cucko29 ...how can I change that?

**Comment by phooton** [comment]
No possible on windows ATM.

**Comment by phooton** [comment]
The C31 algo is very different from C29 on GPU and CPU. It would require lots  of work and it was not worth it this early with only 10% reward and it would run only on Linux. C31 should be supported in next 6 months once the reward goes up and the algorithm is added.
