### ISSUE TITLE
how do i start this automatically on headless systems?

### ISSUE THREAD

**Issue by aleqx** [mozkomor/GrinGoldMiner#45]
Am I missing anything or am I actually supposed to press enter to start mining? This wouldn't be suitable for automated installations (after crashes, etc). There should be an option to start automatically. 

Is there such an option?

Also, can I disable this GUI and allow just a plain console rolling log? Being on ssh via slow a connection works extremely slowly ... again, a problem for automated installations.

**Comment by phooton** [comment]
we are developing GrinPro.io, GGM is open source SW designed for end user

**Comment by aleqx** [comment]
Well, ok (and good luck) ... but that literally doesn't answer any of my questions.

p.s. Your Linux tarball includes all the Windows files as well (unnecessary).

**Comment by phooton** [comment]
It is not suitable for automated installation to farms regardless of UI. Primary target is end user. If that comes, it will be later on.

ps: those are not windows files, those are byte code cross-platform libraries eliminating the need to install dotnet core

**Comment by leifliddy** [comment]
I'm a bit confused here. We are end users. A rolling log is how a Linux application normally outputs logs. It's the default behavior and it's what we're used to. Forcing an end user to manually interact with the miner is just plain inefficient.
