### ISSUE TITLE
Launching miner via systemd service (ubuntu)

### ISSUE THREAD

**Issue by 0xB1000000** [mozkomor/GrinGoldMiner#46]
Got problems getting your miner to run via systemd service (ub 16.04 LTS).

Output:

Jan 15 12:31:36 AMD bash[14564]: Unhandled Exception: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
Jan 15 12:31:36 AMD bash[14564]:    at System.Console.get_KeyAvailable()
Jan 15 12:31:36 AMD bash[14564]:    at Mozkomor.GrinGoldMinerCLI.Program.Main(String[] args) in /home/photon/ggm_BETA3/GrinGoldMiner/src/GrinGoldMinerCLI/Program.cs:line 250

Any workaround for this?

I have approx 12 Miningapps installed, all work when launched via systemd service.

Thanks a ton!

**Comment by leifliddy** [comment]
this issue is constantly being brought up and then subsequently closed out by phooton. 
https://github.com/mozkomor/GrinGoldMiner/issues/45
https://github.com/mozkomor/GrinGoldMiner/issues/43

According to phooton, it's inconceivable that an 'end user' would want to run the miner via a systemd service. Apparently, that only exists within the remit of large mining operations.

**Comment by 0xB1000000** [comment]
Inconceivable? This is how i run thousands of rigs on one of europes biggest farms but ok :)
So, do the math... 5000 rigs not mining devfee for you.. hehe

Well the UI is fine, aslong as systemd doesnt exit due to exception.
I do grab the systemd status tho, in case no other option for logging is available.

But no worries guys, i´m patient. Keep up the good work!
I like your app, will keep checking back.

**Comment by phooton** [comment]
We are making a version specifically designed to do what you ask and more that will be released in a week or so. I'm not sure what else I can say.

**Comment by 0xB1000000** [comment]
Perfekt. Thanks guys!
