### ISSUE TITLE
new issues since release RC3

### ISSUE THREAD

**Issue by 76badrinath** [mozkomor/GrinGoldMiner#47]
Settings: windows 10, x64,  I3-4160cpu @ 3.60ghz,  RAM DDR3 2x 4Go, VRAM 54Go

*unable to create kernel ( never had this issue with previous version )
*out of video memory 
![new issue ggm rc3](https://user-images.githubusercontent.com/46675093/51182220-c55bc980-18cd-11e9-99bf-357cc9dd5bfe.png)

**Comment by donie-inhance** [comment]
My version will not connect, it connects and disconnects. Old version RC1 worked ok in this regard and still works but has the issue where it disconnects after 20 minutes. I presume that problem will go away on Mainnet...

**Comment by camwilmot** [comment]
Also getting "unable to create kernel" with GTX Titan X

**Comment by phooton** [comment]
There was not any change in GPU code, this is not related to new versions. Try to increase your virtual memory as always.

**Comment by zanoo** [comment]
I'm also getting an "Out of video memory" error, although I'm connected to stratum. Using a GTX 1070 on Ubuntu 16.04.

**Comment by Nasjba** [comment]
Same issue

019-01-16T15:38:38Z    ERROR,     Listen errorThe input stream is not a valid binary format. The starting contents (in bytes)...
