### ISSUE TITLE
RX Vega iussue

### ISSUE THREAD

**Issue by criptonomics** [mozkomor/GrinGoldMiner#48]
Detected my 4 cards OK and seems to start mining but always get 0 gps. Tried several pools, connetcion always OK but no hashrate reported. Windows 10. 60GB memory swap size. Applied ENV variable mentioned. AMD Blockchain drivers.

**Comment by senior-pomidorka** [comment]
Same for me

**Comment by tmairegasnighto** [comment]
I am not having this issue on my Vega 64s.  Try using the latest AMD driver instead of the blockchain driver.

**Comment by senior-pomidorka** [comment]
> 
> 
> I am not having this issue on my Vega 64s. Try using the latest AMD driver instead of the blockchain driver.

Thanks, that actually worked for me. Installed latest driver and everything is fine now
