### ISSUE TITLE
GeForce GTX Titan X

### ISSUE THREAD

**Issue by camwilmot** [mozkomor/GrinGoldMiner#49]
Awesome project. Working with with RTX 2080 Ti and 1080 Ti, but getting an error when trying to run GTX Titan X.

**Comment by camwilmot** [comment]
"unable to create kernel"

**Comment by phooton** [comment]
Since it runs on Pascal and Turing, I'm not really sure. That error is very generic. As far as I know, nobody tried it on Titan V before. I don't think I can fix it based on this and the miner does not have more detailed logging this early.
