### ISSUE TITLE
Console not working on win 10

### ISSUE THREAD

**Issue by evlo** [mozkomor/GrinGoldMiner#51]
Miner itself seems to be working
https://i.imgur.com/13xnPER.png

**Comment by Sowiedu** [comment]
Working here (Win10 Version	10.0.17763 Build 1776) but using CUDA solver (GTX 1070, driver 417.35, CUDA driver 10.0.132)

**Comment by urza** [comment]
Console in Windows can sometimes "get paused" by clicking into it with mouse. You just need to press enter with the window in focus and it should start re-drawing again.

**Comment by evlo** [comment]
It is not "paused" console, i even have quick edit disabled

**Comment by evlo** [comment]
so I tried latest version, and for the fun of it even console2 and issue is, that is till just can't refresh the console.
