### ISSUE TITLE
Exception in: StratumConnect.cs # 464 # DisconnectMonitor Message: Object reference not set ...

### ISSUE THREAD

**Issue by zokocx** [mozkomor/GrinGoldMiner#52]
RC3
Connectio to USA stratum (us-east-stratum.grinmint.com) from EU location (ping probably ~250ms).

Doesn't matter if it's SSL port or unsecrure port, and Connection status change from CONNECTED to DISCONNECTED.

Log:
2019-01-15T22:14:49Z    ERROR,     Exception in: StratumConnect.cs # 464 # DisconnectMonitor Message: Object reference not set to an instance of an object.

![image](https://user-images.githubusercontent.com/571644/51213711-f82cae80-191b-11e9-88f0-89dff9bc15cd.png)

**Comment by nymd** [comment]
I started receiving that after the US endpoint had been working; switched to the EU grimmint server and it works.

**Comment by zokocx** [comment]
Apparently at that time US endpoint (grinmint) was down, I didn't notice that.
But still there shouldn't be a exception printed :)

**Comment by urza** [comment]
Fixed in 2.7 release
