### ISSUE TITLE
remote powershell usage seems broken

### ISSUE THREAD

**Issue by cchance27** [mozkomor/GrinGoldMiner#54]
When i run the ggm remotely via powershell on some of my boxes i'm getting an odd error

.\GrinGoldMinerCLI.exe :
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception:

System.InvalidOperationException: Cannot see if a key has been pressed when either
application does not have a console or when console input has been redirected from a
file. Try Console.In.Peek.
   at System.Console.get_KeyAvailable()
   at Mozkomor.GrinGoldMinerCLI.Program.Main(String[] args)

Perhaps the way your accessing the console, is their a way to disable the fancy cli?

**Comment by phooton** [comment]
Not at the moment, will try to sneak that in for next (final) release.

**Comment by urza** [comment]
try to use rolling mode, should solve this
https://github.com/mozkomor/GrinGoldMiner/blob/master/help.md
