### ISSUE TITLE
Grinmint not connecting

### ISSUE THREAD

**Issue by nerdatwork** [mozkomor/GrinGoldMiner#57]
Unlike RC4 or RC3 ver 2.7 is constantly disconnecting for grinmint.com pool

**Comment by phooton** [comment]
Thanks, pulled it back for examination.

**Comment by nerdatwork** [comment]
Their stratum pool was down. How many tries it takes for GGM to switch to secondary pool ?

**Comment by dtlgc** [comment]
2.8beta fixed my problem
