### ISSUE TITLE
Out of memory error for 8gb 1070ti

### ISSUE THREAD

**Issue by samsuh** [mozkomor/GrinGoldMiner#59]
I got this working on a different rig using a single 1080 8gb, but dual 1070ti in sli does not seem to be working. 

> GPU 0: GeForce GTX 1070 Ti    NO MEMORY      Mining at 0.00 gps            Solutions: 0
>        Last Message: 14:02:57:  Out of video memory! Only 7014187008 free
> GPU 1: GeForce GTX 1070 Ti    NO MEMORY      Mining at 0.00 gps            Solutions: 0
>        Last Message: 14:03:01:  Out of video memory! Only 7014187008 free
> 
> ERROR [hit Enter to hide]: GPU GeForce GTX 1070 Ti ID 0: Out of video memory! Only 7014187008 free

**Comment by samsuh** [comment]
i just read in the other issue that the min requirement is: 

7079985152 and i only have 
7014187008 available. 

are there known ways to either increase my available, or to lower the required?

**Comment by samsuh** [comment]
> Install Win 7, Its a problem with WIN 10. Win 10 uses shared memory from your graphic card. I had same problem. When I installed Win 7 no more memory problem.

i understand. is there a known solution to win10?

**Comment by phooton** [comment]
The good new is that GTX1070 is supposed to have enough free memory Win10. My 1070s work fine so are others. The bad news is that I have no idea why your system has much less free video memory on both cards. Oh SLI you say... well I think it is the SLI stuff. Shoudl work with 6GB solver in about a week or so. Cheers

**Comment by vadimDidenko** [comment]
Hi! How many times need for resolve miner for 4 gb cards AMD?

**Comment by rasta-mouse** [comment]
Similar issue for my 8 x 1070 rig.  Only half the cards are able to mine.  They're all exactly the same make and model.

![image](https://user-images.githubusercontent.com/7346521/51414183-63b78b80-1b69-11e9-877c-dc1f17825cb7.png)

**Comment by cjcollard** [comment]
Same issue here - I got 7/8 of my 1070tis running by increasing the page file in windows. Maxed out the hard drive, so I can't get the 8th running yet. Definitely frustrating because its using a tiny fraction of the page file.
