### ISSUE TITLE
Remote powershell fails to generate config

### ISSUE THREAD

**Issue by cchance27** [mozkomor/GrinGoldMiner#60]
below happens as soon as it's run it doesn't wait for the stratum choice, just straight to error tried on 2 separate remote powershell connections

[192.168.1.50]: PS C:\ggm> .\GrinGoldMinerCLI.exe mode=rolling
No config file found, it will be generated now....
Autodetecting GPUs...
Detected 0 suitable nvidia devices
Detected 1 suitable AMD devices
Select minig pool (press number):
[1] Custom stratum address
[2] US-east grinmint.com
[3] EU-west grinmint.com
[4] mwgrinpool.com (open-source, currently invite only)
[5] EU grin-pool.org
Or try some other pools (use option 1): cuckoomine.org grinpool.co sparkpool.com
Enter your mining pool stratum address:
.\GrinGoldMinerCLI.exe :
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Mozkomor.GrinGoldMinerCLI.Program.Main(String[] args)

**Comment by phooton** [comment]
You need give it existing config that you created (sample is in the folder), no other way.

**Comment by cchance27** [comment]
ok will generate it manually
