### ISSUE TITLE
Error code: InvalidWorkItemSize.

### ISSUE THREAD

**Issue by cchance27** [mozkomor/GrinGoldMiner#61]
Not sure if due to the remote powershell sessions i use or the gpu but i'm getting it on both boxes.

ERROR   GPU Ellesmere ID 0: Critical error in main ocl loop The kernel could not be enqueued. Error code: InvalidWorkItemSize.

Someone else said they fixed it by running as admin but i'm already running as an administrator

**Comment by phooton** [comment]
try this and reboot

setx GPU_MAX_WORKGROUP_SIZE 1024

**Comment by cchance27** [comment]
That indeed fixed it thanks
