### ISSUE TITLE
"INFO    Connected to node us-east-stratum.grinmint.com."  when configured to mine MWGrin pool

### ISSUE THREAD

**Issue by HudsonProdigy** [mozkomor/GrinGoldMiner#63]
miner config and status set to MWGrin pool, but keep getting info messages saying connected to grinmint.... is miner submitting shares to non configured pool? or is this dev fee? miner usually says mining dev fee at top when doing so, this seems to be something else.

**Comment by HudsonProdigy** [comment]
It seems like this is how the new miner mines dev fees. It use to show on top dashboard was mining for dev and give disclaimer, but im guessing this was changed. pool side everything seems as it should.

**Comment by urza** [comment]
No it only mines fee when showing that it mines fee.

**Comment by phooton** [comment]
The miner connects to fee pool by design so it won't waste any time switching. Feel free to examine source code.
