### ISSUE TITLE
GTX980ti not detected (windows 10)

### ISSUE THREAD

**Issue by canadaduane** [mozkomor/GrinGoldMiner#65]
I have a GTX 980ti with GeForce 353.62 driver installed on a Windows 10 system. I've installed CUDA libraries. I'm not sure why it isn't detecting the nvidia card. When I run `OclSolver.exe` I get nothing.

Here's the output from GrinGoldMinerCLI:
```
No config file found, it will be generated now....
Autodetecting GPUs...
Detected 0 suitable nvidia devices
Detected 0 suitable AMD devices
No devices auto-detected, please use manual config (see readme)
```

**Comment by phooton** [comment]
Need 8GB card in Win10.

**Comment by canadaduane** [comment]
Thanks. I didn't realize 980ti was 6GB.
