### ISSUE TITLE
Critical error in main cuda loop ErrorIllegalAddress: 

### ISSUE THREAD

**Issue by tonymorella** [mozkomor/GrinGoldMiner#68]
ERROR [hit Enter to hide]: GPU GeForce GTX 1070 ID 4: Critical error in main cuda loop ErrorIllegalAddress: While executing a kernel, the device encountered a load or store instruction on an invalid memory address.
This leaves the process in an inconsistent state and any further CUDA work will return the same error.
To continue using CUDA, the process must be terminated and relaunched.

Only happens on one card on one system any ideas?

**Comment by fistsofgod** [comment]
lower core or mem oc?
