### ISSUE TITLE
Outdated build instructions

### ISSUE THREAD

**Issue by ghost** [mozkomor/GrinGoldMiner#69]
Are the build instructions in `INSTALL.md` still accurate?

First, it mentions to create a folder called _edges_. But the official release does not use that folder and it does not create any ramdisk after it starts.

Second, I am running Ubuntu 18.04 and I have installed .NET Core 2.2 SDK and Runtime. When I try to build the application I receive the following error:
`/usr/share/dotnet/sdk/2.2.103/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.`

Third, how can I use Mono to build the application? Maybe this is would be easier than solving the second issue.

EDIT: I discovered that I can use Mono to build the application with the following command:
`xbuild publish --self-contained --runtime ubuntu.18.04-x64 --configuration "Release"`
But it produces even more errors and there it is not a solution.

**Comment by timetoseek** [comment]
Also please update build instructions to include macOS... Hoping this can be build using the macOS version of .Net core (2.2).
