### ISSUE TITLE
Please put a delay between bringing each GPU online so it doesnt overload the CPU. 

### ISSUE THREAD

**Issue by fistsofgod** [mozkomor/GrinGoldMiner#70]
please enforce initialization of 1 gpu at a time to prevent CPU overload on starting, or a command line option to enable starting each GPU in config one at a time. over 5 GPU starting all at once overloads my CPU (I3-7100)
Windows 10, latest GGM

**Comment by phooton** [comment]
I'm not sure what you mean, there is 4 second delay for every GPU init since early betas. GPUs should appear in second intervals. All solvers starting at once after that is no issue for CPU.

**Comment by fistsofgod** [comment]
im referring to GPU's coming "ONLINE" a delay between GPU going green online state. thats when my CPU is taxed the most
