### ISSUE TITLE
Vega 56 and Vega 64 8-GB cards iussue

### ISSUE THREAD

**Issue by artkor82** [mozkomor/GrinGoldMiner#72]
Hello!

I have Vega 56 and Vega 64 8-GB cards. Cards demonstrate a good hashrate, but the number of solutions is very different from numbers of accepted Shares.

This happens absolutely on any versions of the miner, I tried everything in turn.

Windows 10 64, Virtual memory is increased.
AMD driver : Adrenalin 2019 Edition 19.1.1  (before that I tried 18.5.1, 18.12.12, but the problem is on all versions)

![default](https://user-images.githubusercontent.com/45110597/51427013-40d9b580-1c03-11e9-93e7-e1751bb87ced.png)

![2019-01-19_16-00-03](https://user-images.githubusercontent.com/45110597/51427014-564edf80-1c03-11e9-9650-7f026c7643d0.png)

**Comment by artkor82** [comment]
In earlier versions of the miner, the problem appears as follows:

![2019-01-19_16-03-10](https://user-images.githubusercontent.com/45110597/51427053-e7be5180-1c03-11e9-8af7-45688e34e95f.png)

**Comment by phooton** [comment]
Graph solution is not a share. Pools requests only high difficulty shares and get them. There is no issue with that.
