### ISSUE TITLE
2.8 - console still hangs on windows10 (not 1809 thought)

### ISSUE THREAD

**Issue by evlo** [mozkomor/GrinGoldMiner#73]
Same as the issue you closed before https://github.com/mozkomor/GrinGoldMiner/issues/51

video
https://www.dropbox.com/s/hshow7mar1kehpo/grin_gold_miner_windows_10.swf?dl=0

I know latest 1809 windows have different console, so maybe it works there.

Also console slowly scrolls down to black section of it after it stops updating :)

**Comment by urza** [comment]
I will add some more share info into rolling mode later into some future release, so you are at least able to see number of shares..

**Comment by sicktraderman** [comment]
i got some messages in rolling mode but im now getting mad stale shares 
"WARNING Solution submitted too late"
