### ISSUE TITLE
Nvidia 1060 6GB not detected on Linux - not working on Windows10

### ISSUE THREAD

**Issue by gapeman** [mozkomor/GrinGoldMiner#76]
My nvidia 1060 6GB didn't get recognized on my Linux rig. I didn't try to set it up manually though.
I tried setting it up manually in Windows 10 and the available memory was at around 5.2 GB according to your miner, which wasn't enough.

Just reporting in case it helps you with anything.
p.s. willing to test and help with nvidia 10xx cards

**Comment by gapeman** [comment]
p.p.s my linux rig doesn't display submitted shares and other info properly - I just see a black window. It stops updating after a few seconds - doesn't matter if I connect to a pool or not. It's very hard to test which cards work and which don't, that's why I just gave up with my 1060. I have 10 cards on that setup, if that makes any difference - 9 of them are hashing with your program and they all seem to work fine.

**Comment by phooton** [comment]
Please read the first sentence on the main github page

>Miner supports all AMD and NVIDIA 6GB cards. 6GB cards need Linux or Windows7 at the moment because Windows reserves too much memory on those cards. 

Tried P106 on Windows and Linux and worked nicely. You need drivers with CUDA 9.1 for it to work on Linux. Auto-detect may fail if you don't.

**Comment by gapeman** [comment]
Yes I did read that. Like I said, reporting in case it helps you with anything.

Do I need CUDA 9.1 specifically on Linux or can it be 9.2/10 ?
