### ISSUE TITLE
AMD R9 380

### ISSUE THREAD

**Issue by killua99** [mozkomor/GrinGoldMiner#83]
Plaform: Ubuntu 18.04 LTS
GGM Version: 2.8
AMD Drivers: amdgpu pro --headless
lib installed:
- ocl-icd-libopencl 2.2.11
- ocl-icd-opencl-dev 2.2.11

Error running ./OclSolver

`1/30/19 10:40:44 PM:     Error, Failed to get OpenCL platform list,`

**Comment by le-dawg** [comment]
Did you test with other cards ? I do not think this is a GGM issue. Try GrinPro and bminer. If they too fail then you hve a driver problem.

**Comment by bovcan** [comment]
yup
