### ISSUE TITLE
Good day. Please Fix for the NiceHash for grincuckaroo29/31

### ISSUE THREAD

**Issue by ruslan2109** [mozkomor/GrinGoldMiner#85]
Please Fix for the NiceHash for grincuckaroo29/31.
Thanks

**Comment by phooton** [comment]
Nicehash added arbitrary complications to the stratum protocol and made their system incompatible with all grin miners from the first minute. We'll have a look once we get some time... It kind-of breaks everything for no good reason.

**Comment by phooton** [comment]
See here... https://github.com/mimblewimble/grin-miner/pull/178

Will wait and see what happens here first. They could change the protocol again.

**Comment by sebseb7** [comment]
why wait? it's a simple change and allow to deliver share to nicehash using GGM. nichhash will not make further changes to their protocol.
